### ISSUE TITLE
Not all members of the thread are being added to rep dropdown

### ISSUE THREAD

**Issue by Nuckerr** [learnspigot/discord-bot#4]
On thread close, not all members of a thread are being added to the rep selection dropdown. Could be related to the bot restarting.

**Comment by HDcookie** [comment]
I've found JDA does some weird things with getting users, mostly due to discord making it more complicated.  I found that enabling MemberChachePolicy and ChunkingFilter fixed it for me, though because this is mostly koltlin I could be 100% wrong and it has nothing todo with this case.  Anyways, this is how I fixed it in my bot:
`JDA api = JDABuilder.createDefault(tokenStr)
                .enableIntents(GatewayIntent.GUILD_MEMBERS, GatewayIntent.MESSAGE_CONTENT)
                .setMemberCachePolicy(MemberCachePolicy.ALL)
                .setChunkingFilter(ChunkingFilter.ALL)
                .build();`

**Comment by Nuckerr** [comment]
I will integrate this, thank you so much!

**Comment by Nuckerr** [comment]
Sadly, we have all those settings enabled already
![image](https://user-images.githubusercontent.com/62883418/207692721-6c0bea47-55c6-4321-9522-8f9920b58e06.png)

**Comment by HDcookie** [comment]
That sucks, I don't know why it still doesn't work. One workaround might be to manually record everyone who sends a message in the thread, but other than that I don't know how to fix the bug. Sorry for the inconvenience.

**Comment by Nuckerr** [comment]
[c590a1f](https://github.com/learnspigot/discord-bot/commit/c590a1f06233be0106c8253f8c9f6e8e2750e1db)
I was using `ThreadChannel#getThreadMembers()` which only returns cached members and I changed that to `channel.retrieveThreadMembers()`
